name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            latexmk

      - name: Compile LaTeX (conference_101719.tex)
        run: |
          mkdir -p build
          latexmk -pdf -output-directory=build conference_101719.tex

      - name: Move PDF to repo root
        run: |
          cp build/conference_101719.pdf ./conference_101719.pdf

      - name: Commit PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-build PDF from conference_101719.tex"
          file_pattern: "conference_101719.pdf"
